import os
import io
import base64
import numpy as np
import cv2
from fastapi import FastAPI, HTTPException, Body
from typing import List
from pydantic import BaseModel
from deepface import DeepFace
from fastapi.middleware.cors import CORSMiddleware
import urllib.request

app = FastAPI(title="PresensiKu Face Verification API")

# Setup CORS to allow requests from the React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # For production, restrict this to frontend URL
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class VerificationRequest(BaseModel):
    captured_image_base64: str
    reference_image_url: str

class CheckDuplicateRequest(BaseModel):
    captured_image_base64: str
    reference_urls: List[str]

class DetectFaceRequest(BaseModel):
    captured_image_base64: str

def enhance_lighting(img):
    """
    Enhance face lighting for both overexposed and underexposed conditions using CLAHE on LAB color space.
    """
    try:
        # Convert to LAB color space
        lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
        l, a, b = cv2.split(lab)
        
        # Apply CLAHE to L-channel
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
        cl = clahe.apply(l)
        
        # Merge channels
        limg = cv2.merge((cl,a,b))
        
        # Convert back to BGR
        enhanced_img = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
        return enhanced_img
    except Exception as e:
        print(f"Warning: Lighting enhancement failed, using original image. Error: {str(e)}")
        return img

def base64_to_cv2(base64_string: str):
    """Convert base64 string to OpenCV image"""
    if ',' in base64_string:
        base64_string = base64_string.split(',')[1]
    try:
        img_data = base64.b64decode(base64_string)
        nparr = np.frombuffer(img_data, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        if img is None:
            raise ValueError("Failed to decode base64 to image")
        return img
    except Exception as e:
        raise Exception(f"Error processing base64 image: {str(e)}")

def url_to_cv2(url: str):
    """Fetch image from URL and convert to OpenCV image"""
    try:
        # If running in Docker, we need to map URLs so backend can reach Supabase
        if os.getenv("IN_DOCKER") == "true":
            if url.startswith("/supabase/"):
                # Handle relative URLs generated by frontend proxy config
                url = url.replace("/supabase/", "http://supabase_kong_Frontend:8000/", 1)
            else:
                # Handle absolute URLs from old records
                url = url.replace("http://127.0.0.1:54331", "http://supabase_kong_Frontend:8000")
                url = url.replace("127.0.0.1", "host.docker.internal").replace("localhost", "host.docker.internal")
        
        req = urllib.request.urlopen(url)
        arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
        img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        if img is None:
            raise ValueError("Failed to decode image from URL")
        return img
    except Exception as e:
        raise Exception(f"Failed to load image from URL: {url}, {str(e)}")

@app.get("/")
def health_check():
    return {"status": "ok", "message": "Face Verification API is running"}

@app.post("/verify")
async def verify_face(req: VerificationRequest):
    try:
        # Prepare images
        img1 = base64_to_cv2(req.captured_image_base64)
        
        # Enhance lighting (fix too dark or too bright)
        img1 = enhance_lighting(img1)
        
        img2 = url_to_cv2(req.reference_image_url)

        # Run DeepFace verification
        # Using Facenet512 for much higher accuracy to prevent false positives.
        result = DeepFace.verify(
            img1_path=img1, 
            img2_path=img2, 
            model_name="Facenet512", 
            detector_backend="ssd",
            enforce_detection=True # Set to True to STRICTLY enforce that a face must be detected, otherwise reject!
        )
        
        return {
            "verified": bool(result.get("verified", False)),
            "distance": float(result.get("distance", 1.0)),
            "threshold": float(result.get("threshold", 0.0)),
            "model": result.get("model", "Facenet")
        }
    except Exception as e:
        print(f"Error during verification: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/check-duplicate")
async def check_duplicate(req: CheckDuplicateRequest):
    try:
        if not req.reference_urls:
            return {"is_duplicate": False, "duplicate_url": None}

        # Prepare captured image
        img1 = base64_to_cv2(req.captured_image_base64)
        img1 = enhance_lighting(img1)

        # 1. Pre-check: Ensure there is actually a face in the captured image
        try:
            # We just extract faces to see if it passes
            DeepFace.extract_faces(img_path=img1, detector_backend="ssd", enforce_detection=True)
        except ValueError:
            # DeepFace throws ValueError if no face is detected
            raise HTTPException(status_code=400, detail="Wajah tidak terdeteksi di foto yang Anda ambil. Silakan foto ulang dengan pencahayaan yang baik.")

        # 2. If face exists, loop through reference URLs
        for url in req.reference_urls:
            try:
                img2 = url_to_cv2(url)
                result = DeepFace.verify(
                    img1_path=img1, 
                    img2_path=img2, 
                    model_name="Facenet512", 
                    detector_backend="ssd",
                    enforce_detection=True
                )
                if result.get("verified", False):
                    return {"is_duplicate": True, "duplicate_url": url}
            except Exception as e:
                print(f"Skipping url {url} due to error: {str(e)}")
                continue

        return {"is_duplicate": False, "duplicate_url": None}
    except HTTPException:
        # Re-raise HTTP exceptions so they retain their status code (like 400)
        raise
    except Exception as e:
        print(f"Error during duplicate check: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/detect")
async def detect_face(req: DetectFaceRequest):
    try:
        # Prepare captured image
        img1 = base64_to_cv2(req.captured_image_base64)
        img1 = enhance_lighting(img1)

        try:
            # We just extract faces to see if it passes
            DeepFace.extract_faces(img_path=img1, detector_backend="ssd", enforce_detection=True)
            return {"face_detected": True}
        except ValueError:
            # DeepFace throws ValueError if no face is detected
            raise HTTPException(status_code=400, detail="Wajah tidak terdeteksi di foto yang Anda ambil. Pastikan wajah terlihat jelas dan pencahayaan cukup.")
    except HTTPException:
        raise
    except Exception as e:
        print(f"Error during face detection: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    # Preload the DeepFace model by running a dummy verification
    # This ensures the first API request doesn't timeout while downloading the model
    try:
        print("Preloading DeepFace models...")
        dummy_img = np.zeros((224, 224, 3), dtype=np.uint8)
        try:
            DeepFace.verify(img1_path=dummy_img, img2_path=dummy_img, model_name="Facenet512", detector_backend="ssd", enforce_detection=False)
        except:
            pass
        print("DeepFace models loaded successfully!")
    except Exception as e:
        print(f"Model preload note: {str(e)}")
        
    print("Starting FastAPI server...")
    uvicorn.run(app, host="0.0.0.0", port=8000)
